### ISSUE TITLE
Get content from Gutenberg API

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/nextjs-starter#10]
Related: https://github.com/trendwerk/headless-wordpress/issues/6

**Comment by sboerrigter** [comment]
I reopen this because I think we are still not benefiting from the Gutenberg GraphQL API. We still get all content from one single `content` field. According to the [plugin documentation](https://wp-graphql-gutenberg.netlify.app/getting-started/how-to-query/) we can query the gutenberg blocks something like this:

```
{
  page(id: "voorbeeld-pagina", idType: URI) {
    title
    blocks {
      name
        ... on CoreParagraphBlock {
          attributes {
              ... on CoreParagraphBlockAttributes {
                  content
              }
          }
      }
    }
  }
}
```

If we do this we can create a separate component for each block type we support and have more control over the HTML output.

**Comment by luukdv** [comment]
@sboerrigter Closing this one, as discussed.

**Comment by sboerrigter** [comment]
Reopening this one, styling is not done.
