### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/nextjs-starter#11]
Can we use a page as the homepage based on the WordPress homepage setting?

**Comment by luukdv** [comment]
I've registered a `templateType` for all pages, but right now it's not possible yet to register a custom GraphQL connection in wp-graphql. When that's added, we can do this on the front page:

```
query MyQuery {
  pages(where: {templateType: "page_on_front"}) {
    edges {
      node { … }
    }
  }
}

```
