### ISSUE TITLE
Refactor context

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/nextjs-starter#25]
> je hebt nu alles in 1 context geplaatst die heel hoog staat waardoor de hele tree telkens moet re-renderen als 1 context value verandert, context kun je het beste opsplitsen in zo veel mogelijk losse contexts en zo laag mogelijk in de tree plaatsen

**Comment by sboerrigter** [comment]
Related:
>  op verschillende plekken (zoals Header.js) staat iets als const { post } = useContext(Context) maar dat bestaat niet en geeft een error

**Comment by luukdv** [comment]
https://github.com/trendwerk/nextjs-starter/pull/28
