### ISSUE TITLE
Images without crop

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/nextjs-starter#4]
Allow images without a `width` or `height` argument to get the uncropped image.

**Comment by luukdv** [comment]
Leaving out the `height` prop is now supported (https://github.com/trendwerk/nextjs-starter/pull/34). Do you think the option to leave out `width` and only setting `height` has a use case at the moment? This would add some complexity.

**Comment by sboerrigter** [comment]
No that's not important.
