### ISSUE TITLE
Tap targets: link heights

### ISSUE THREAD

**Issue by luukdv** [trendwerk/nextjs-starter#62]
Links should have a height of at least `48` pixels. An example offender:

<img width="185" alt="Screenshot 2020-08-20 at 10 49 00" src="https://user-images.githubusercontent.com/5585947/90748741-dd2dd780-e2d2-11ea-8bbf-9b882bd153f8.png">

**Comment by sboerrigter** [comment]
48px is pretty large. Do we really want to follow this advice? Then how do we cope with inline links?

**Comment by luukdv** [comment]
Fine by me to close this one 👍
